# Generated by Django 4.0.6 on 2024-10-23 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Votaciones', '0002_candidato_ci_alter_votante_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='voto',
            name='cargo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Votaciones.cargo'),
        ),
    ]
